// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coco_interference_scores.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CoCoInterferenceScores struct {
	DevilPenalty         uint32   `protobuf:"varint,1,opt,name=devil_penalty,json=devilPenalty,proto3" json:"devil_penalty,omitempty"`
	RabbitPenalty        uint32   `protobuf:"varint,2,opt,name=rabbit_penalty,json=rabbitPenalty,proto3" json:"rabbit_penalty,omitempty"`
	SheepPenalty         uint32   `protobuf:"varint,3,opt,name=sheep_penalty,json=sheepPenalty,proto3" json:"sheep_penalty,omitempty"`
	TurtlePenalty        uint32   `protobuf:"varint,4,opt,name=turtle_penalty,json=turtlePenalty,proto3" json:"turtle_penalty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoCoInterferenceScores) Reset()         { *m = CoCoInterferenceScores{} }
func (m *CoCoInterferenceScores) String() string { return proto.CompactTextString(m) }
func (*CoCoInterferenceScores) ProtoMessage()    {}
func (*CoCoInterferenceScores) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1bf212dcb0808ac, []int{0}
}

func (m *CoCoInterferenceScores) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoCoInterferenceScores.Unmarshal(m, b)
}
func (m *CoCoInterferenceScores) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoCoInterferenceScores.Marshal(b, m, deterministic)
}
func (m *CoCoInterferenceScores) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoCoInterferenceScores.Merge(m, src)
}
func (m *CoCoInterferenceScores) XXX_Size() int {
	return xxx_messageInfo_CoCoInterferenceScores.Size(m)
}
func (m *CoCoInterferenceScores) XXX_DiscardUnknown() {
	xxx_messageInfo_CoCoInterferenceScores.DiscardUnknown(m)
}

var xxx_messageInfo_CoCoInterferenceScores proto.InternalMessageInfo

func (m *CoCoInterferenceScores) GetDevilPenalty() uint32 {
	if m != nil {
		return m.DevilPenalty
	}
	return 0
}

func (m *CoCoInterferenceScores) GetRabbitPenalty() uint32 {
	if m != nil {
		return m.RabbitPenalty
	}
	return 0
}

func (m *CoCoInterferenceScores) GetSheepPenalty() uint32 {
	if m != nil {
		return m.SheepPenalty
	}
	return 0
}

func (m *CoCoInterferenceScores) GetTurtlePenalty() uint32 {
	if m != nil {
		return m.TurtlePenalty
	}
	return 0
}

func init() {
	proto.RegisterType((*CoCoInterferenceScores)(nil), "proto.CoCoInterferenceScores")
}

func init() { proto.RegisterFile("coco_interference_scores.proto", fileDescriptor_b1bf212dcb0808ac) }

var fileDescriptor_b1bf212dcb0808ac = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0xce, 0x4f, 0xce,
	0x8f, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0x4a, 0x4b, 0x2d, 0x4a, 0xcd, 0x4b, 0x4e, 0x8d, 0x2f, 0x4e,
	0xce, 0x2f, 0x4a, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x1b,
	0x18, 0xb9, 0xc4, 0x9c, 0xf3, 0x9d, 0xf3, 0x3d, 0x91, 0x14, 0x06, 0x83, 0xd5, 0x09, 0x29, 0x73,
	0xf1, 0xa6, 0xa4, 0x96, 0x65, 0xe6, 0xc4, 0x17, 0xa4, 0xe6, 0x25, 0xe6, 0x94, 0x54, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0xf0, 0x06, 0xf1, 0x80, 0x05, 0x03, 0x20, 0x62, 0x42, 0xaa, 0x5c, 0x7c, 0x45,
	0x89, 0x49, 0x49, 0x99, 0x25, 0x70, 0x55, 0x4c, 0x60, 0x55, 0xbc, 0x10, 0x51, 0x98, 0x32, 0x65,
	0x2e, 0xde, 0xe2, 0x8c, 0xd4, 0xd4, 0x02, 0xb8, 0x2a, 0x66, 0x88, 0x59, 0x60, 0x41, 0x24, 0xb3,
	0x4a, 0x4a, 0x8b, 0x4a, 0x72, 0x52, 0xe1, 0xaa, 0x58, 0x20, 0x66, 0x41, 0x44, 0xa1, 0xca, 0x92,
	0xd8, 0xc0, 0x2e, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x38, 0x07, 0x38, 0xcb, 0xe2, 0x00,
	0x00, 0x00,
}
