// Code generated by protoc-gen-go. DO NOT EDIT.
// source: label_selector.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LabelSelector_SelectorType int32

const (
	LabelSelector_IN_SET         LabelSelector_SelectorType = 0
	LabelSelector_NOT_IN_SET     LabelSelector_SelectorType = 1
	LabelSelector_EXISTS_KEY     LabelSelector_SelectorType = 2
	LabelSelector_NOT_EXISTS_KEY LabelSelector_SelectorType = 3
)

var LabelSelector_SelectorType_name = map[int32]string{
	0: "IN_SET",
	1: "NOT_IN_SET",
	2: "EXISTS_KEY",
	3: "NOT_EXISTS_KEY",
}

var LabelSelector_SelectorType_value = map[string]int32{
	"IN_SET":         0,
	"NOT_IN_SET":     1,
	"EXISTS_KEY":     2,
	"NOT_EXISTS_KEY": 3,
}

func (x LabelSelector_SelectorType) String() string {
	return proto.EnumName(LabelSelector_SelectorType_name, int32(x))
}

func (LabelSelector_SelectorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2e817eb3c90cb08b, []int{0, 0}
}

type LabelSelector struct {
	Type                 LabelSelector_SelectorType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.LabelSelector_SelectorType" json:"type,omitempty"`
	Key                  string                     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string                   `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *LabelSelector) Reset()         { *m = LabelSelector{} }
func (m *LabelSelector) String() string { return proto.CompactTextString(m) }
func (*LabelSelector) ProtoMessage()    {}
func (*LabelSelector) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e817eb3c90cb08b, []int{0}
}

func (m *LabelSelector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelSelector.Unmarshal(m, b)
}
func (m *LabelSelector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelSelector.Marshal(b, m, deterministic)
}
func (m *LabelSelector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelSelector.Merge(m, src)
}
func (m *LabelSelector) XXX_Size() int {
	return xxx_messageInfo_LabelSelector.Size(m)
}
func (m *LabelSelector) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelSelector.DiscardUnknown(m)
}

var xxx_messageInfo_LabelSelector proto.InternalMessageInfo

func (m *LabelSelector) GetType() LabelSelector_SelectorType {
	if m != nil {
		return m.Type
	}
	return LabelSelector_IN_SET
}

func (m *LabelSelector) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LabelSelector) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.LabelSelector_SelectorType", LabelSelector_SelectorType_name, LabelSelector_SelectorType_value)
	proto.RegisterType((*LabelSelector)(nil), "proto.LabelSelector")
}

func init() { proto.RegisterFile("label_selector.proto", fileDescriptor_2e817eb3c90cb08b) }

var fileDescriptor_2e817eb3c90cb08b = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0x49, 0x4c, 0x4a,
	0xcd, 0x89, 0x2f, 0x4e, 0xcd, 0x49, 0x4d, 0x2e, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x05, 0x53, 0x4a, 0x07, 0x18, 0xb9, 0x78, 0x7d, 0x40, 0xf2, 0xc1, 0x50, 0x69, 0x21,
	0x53, 0x2e, 0x96, 0x92, 0xca, 0x82, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x45, 0x88,
	0x72, 0x3d, 0x14, 0x35, 0x7a, 0x30, 0x46, 0x48, 0x65, 0x41, 0x6a, 0x10, 0x58, 0xb9, 0x90, 0x00,
	0x17, 0x73, 0x76, 0x6a, 0xa5, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0x29, 0x24, 0xc6,
	0xc5, 0x56, 0x96, 0x98, 0x53, 0x9a, 0x5a, 0x2c, 0xc1, 0xac, 0xc0, 0xac, 0xc1, 0x19, 0x04, 0xe5,
	0x29, 0xf9, 0x71, 0xf1, 0x20, 0xeb, 0x17, 0xe2, 0xe2, 0x62, 0xf3, 0xf4, 0x8b, 0x0f, 0x76, 0x0d,
	0x11, 0x60, 0x10, 0xe2, 0xe3, 0xe2, 0xf2, 0xf3, 0x0f, 0x89, 0x87, 0xf2, 0x19, 0x41, 0x7c, 0xd7,
	0x08, 0xcf, 0xe0, 0x90, 0xe0, 0x78, 0x6f, 0xd7, 0x48, 0x01, 0x26, 0x21, 0x21, 0x2e, 0x3e, 0x90,
	0x3c, 0x92, 0x18, 0x73, 0x12, 0x1b, 0xd8, 0x85, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59,
	0x99, 0x14, 0xa2, 0xe8, 0x00, 0x00, 0x00,
}
