// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource_stats.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResourceStats struct {
	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Timestamp  uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The first entry is the cpu usage of cpu0 and so on.
	CpusStats []*CpuStats `protobuf:"bytes,3,rep,name=cpus_stats,json=cpusStats,proto3" json:"cpus_stats,omitempty"`
	// Memory stats (in KB).
	MemAllocatable int64 `protobuf:"varint,4,opt,name=mem_allocatable,json=memAllocatable,proto3" json:"mem_allocatable,omitempty"`
	MemCapacity    int64 `protobuf:"varint,5,opt,name=mem_capacity,json=memCapacity,proto3" json:"mem_capacity,omitempty"`
	// Memory stats (fraction of total).
	MemReservation float64 `protobuf:"fixed64,6,opt,name=mem_reservation,json=memReservation,proto3" json:"mem_reservation,omitempty"`
	MemUtilization float64 `protobuf:"fixed64,7,opt,name=mem_utilization,json=memUtilization,proto3" json:"mem_utilization,omitempty"`
	// Disk stats in KB
	DiskBw int64 `protobuf:"varint,8,opt,name=disk_bw,json=diskBw,proto3" json:"disk_bw,omitempty"`
	// Network stats in KB
	NetRxBw              int64    `protobuf:"varint,9,opt,name=net_rx_bw,json=netRxBw,proto3" json:"net_rx_bw,omitempty"`
	NetTxBw              int64    `protobuf:"varint,10,opt,name=net_tx_bw,json=netTxBw,proto3" json:"net_tx_bw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceStats) Reset()         { *m = ResourceStats{} }
func (m *ResourceStats) String() string { return proto.CompactTextString(m) }
func (*ResourceStats) ProtoMessage()    {}
func (*ResourceStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e63005a7ba86f07, []int{0}
}

func (m *ResourceStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceStats.Unmarshal(m, b)
}
func (m *ResourceStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceStats.Marshal(b, m, deterministic)
}
func (m *ResourceStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceStats.Merge(m, src)
}
func (m *ResourceStats) XXX_Size() int {
	return xxx_messageInfo_ResourceStats.Size(m)
}
func (m *ResourceStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceStats.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceStats proto.InternalMessageInfo

func (m *ResourceStats) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *ResourceStats) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ResourceStats) GetCpusStats() []*CpuStats {
	if m != nil {
		return m.CpusStats
	}
	return nil
}

func (m *ResourceStats) GetMemAllocatable() int64 {
	if m != nil {
		return m.MemAllocatable
	}
	return 0
}

func (m *ResourceStats) GetMemCapacity() int64 {
	if m != nil {
		return m.MemCapacity
	}
	return 0
}

func (m *ResourceStats) GetMemReservation() float64 {
	if m != nil {
		return m.MemReservation
	}
	return 0
}

func (m *ResourceStats) GetMemUtilization() float64 {
	if m != nil {
		return m.MemUtilization
	}
	return 0
}

func (m *ResourceStats) GetDiskBw() int64 {
	if m != nil {
		return m.DiskBw
	}
	return 0
}

func (m *ResourceStats) GetNetRxBw() int64 {
	if m != nil {
		return m.NetRxBw
	}
	return 0
}

func (m *ResourceStats) GetNetTxBw() int64 {
	if m != nil {
		return m.NetTxBw
	}
	return 0
}

type CpuStats struct {
	// CPU stats in millicores.
	CpuAllocatable int64 `protobuf:"varint,1,opt,name=cpu_allocatable,json=cpuAllocatable,proto3" json:"cpu_allocatable,omitempty"`
	CpuCapacity    int64 `protobuf:"varint,2,opt,name=cpu_capacity,json=cpuCapacity,proto3" json:"cpu_capacity,omitempty"`
	// CPU stats (fraction of total).
	CpuReservation       float64  `protobuf:"fixed64,3,opt,name=cpu_reservation,json=cpuReservation,proto3" json:"cpu_reservation,omitempty"`
	CpuUtilization       float64  `protobuf:"fixed64,4,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CpuStats) Reset()         { *m = CpuStats{} }
func (m *CpuStats) String() string { return proto.CompactTextString(m) }
func (*CpuStats) ProtoMessage()    {}
func (*CpuStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e63005a7ba86f07, []int{1}
}

func (m *CpuStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CpuStats.Unmarshal(m, b)
}
func (m *CpuStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CpuStats.Marshal(b, m, deterministic)
}
func (m *CpuStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CpuStats.Merge(m, src)
}
func (m *CpuStats) XXX_Size() int {
	return xxx_messageInfo_CpuStats.Size(m)
}
func (m *CpuStats) XXX_DiscardUnknown() {
	xxx_messageInfo_CpuStats.DiscardUnknown(m)
}

var xxx_messageInfo_CpuStats proto.InternalMessageInfo

func (m *CpuStats) GetCpuAllocatable() int64 {
	if m != nil {
		return m.CpuAllocatable
	}
	return 0
}

func (m *CpuStats) GetCpuCapacity() int64 {
	if m != nil {
		return m.CpuCapacity
	}
	return 0
}

func (m *CpuStats) GetCpuReservation() float64 {
	if m != nil {
		return m.CpuReservation
	}
	return 0
}

func (m *CpuStats) GetCpuUtilization() float64 {
	if m != nil {
		return m.CpuUtilization
	}
	return 0
}

func init() {
	proto.RegisterType((*ResourceStats)(nil), "proto.ResourceStats")
	proto.RegisterType((*CpuStats)(nil), "proto.CpuStats")
}

func init() { proto.RegisterFile("resource_stats.proto", fileDescriptor_4e63005a7ba86f07) }

var fileDescriptor_4e63005a7ba86f07 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xbd, 0x4e, 0xf3, 0x30,
	0x18, 0x85, 0xe5, 0xa6, 0x7f, 0x79, 0xfb, 0x7d, 0x54, 0xb2, 0x90, 0xb0, 0x10, 0x12, 0xa1, 0x0b,
	0x99, 0x3a, 0xc0, 0x15, 0xd0, 0x4e, 0xac, 0x06, 0xe6, 0xc8, 0x75, 0x3d, 0x58, 0xc4, 0x8d, 0x15,
	0xdb, 0x34, 0x70, 0x45, 0xdc, 0x1c, 0xf7, 0x80, 0x6c, 0x37, 0x3f, 0x74, 0x8a, 0x72, 0xce, 0x13,
	0x9f, 0x3c, 0x09, 0x5c, 0xd6, 0xc2, 0x54, 0xae, 0xe6, 0xa2, 0x30, 0x96, 0x59, 0xb3, 0xd6, 0x75,
	0x65, 0x2b, 0x3c, 0x09, 0x97, 0xd5, 0xcf, 0x08, 0xfe, 0xd3, 0x53, 0xff, 0xe2, 0x6b, 0x7c, 0x0b,
	0x8b, 0xee, 0x01, 0xb9, 0x27, 0x28, 0x43, 0x79, 0x4a, 0xa1, 0x8d, 0x9e, 0xf7, 0xf8, 0x06, 0x52,
	0x2b, 0x95, 0x30, 0x96, 0x29, 0x4d, 0x46, 0x19, 0xca, 0xc7, 0xb4, 0x0f, 0xf0, 0x1a, 0x80, 0x6b,
	0x67, 0xe2, 0x16, 0x49, 0xb2, 0x24, 0x5f, 0x3c, 0x2c, 0xe3, 0xe6, 0x7a, 0xab, 0x5d, 0xd8, 0xa0,
	0xa9, 0x47, 0xe2, 0xdc, 0x3d, 0x2c, 0x95, 0x50, 0x05, 0x2b, 0xcb, 0x8a, 0x33, 0xcb, 0x76, 0xa5,
	0x20, 0xe3, 0x0c, 0xe5, 0x09, 0xbd, 0x50, 0x42, 0x3d, 0xf5, 0x29, 0xbe, 0x83, 0x7f, 0x1e, 0xe4,
	0x4c, 0x33, 0x2e, 0xed, 0x27, 0x99, 0x04, 0x6a, 0xa1, 0x84, 0xda, 0x9e, 0xa2, 0xf6, 0xac, 0x5a,
	0x18, 0x51, 0x7f, 0x30, 0x2b, 0xab, 0x03, 0x99, 0x66, 0x28, 0x47, 0xe1, 0x2c, 0xda, 0xa7, 0x2d,
	0xe8, 0xac, 0x2c, 0xe5, 0x57, 0x04, 0x67, 0x1d, 0xf8, 0xd6, 0xa7, 0xf8, 0x0a, 0x66, 0x7b, 0x69,
	0xde, 0x8b, 0xdd, 0x91, 0xcc, 0xc3, 0xde, 0xd4, 0xdf, 0x6e, 0x8e, 0xf8, 0x1a, 0xd2, 0x83, 0xb0,
	0x45, 0xdd, 0xf8, 0x2a, 0x0d, 0xd5, 0xec, 0x20, 0x2c, 0x6d, 0xfa, 0xce, 0x86, 0x0e, 0xba, 0xee,
	0xb5, 0xd9, 0x1c, 0x57, 0xdf, 0x08, 0xe6, 0xed, 0x67, 0xf0, 0xaf, 0xc1, 0xb5, 0xfb, 0xe3, 0x8e,
	0xa2, 0x3b, 0xd7, 0xee, 0xcc, 0xdd, 0x83, 0x9d, 0xfb, 0x28, 0xba, 0x73, 0xed, 0x86, 0xee, 0x1e,
	0x19, 0xba, 0x27, 0x51, 0x89, 0x6b, 0x77, 0xe6, 0xee, 0xc1, 0xa1, 0xfb, 0xb8, 0x03, 0x07, 0xee,
	0xbb, 0x69, 0xf8, 0x69, 0x8f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xf0, 0xe0, 0xf7, 0x40,
	0x02, 0x00, 0x00,
}
