// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource_topology_node_desc.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResourceTopologyNodeDescriptor struct {
	ResourceDesc         *ResourceDescriptor               `protobuf:"bytes,1,opt,name=resource_desc,json=resourceDesc,proto3" json:"resource_desc,omitempty"`
	Children             []*ResourceTopologyNodeDescriptor `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	ParentId             string                            `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ResourceTopologyNodeDescriptor) Reset()         { *m = ResourceTopologyNodeDescriptor{} }
func (m *ResourceTopologyNodeDescriptor) String() string { return proto.CompactTextString(m) }
func (*ResourceTopologyNodeDescriptor) ProtoMessage()    {}
func (*ResourceTopologyNodeDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_7efed64a16c51499, []int{0}
}

func (m *ResourceTopologyNodeDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceTopologyNodeDescriptor.Unmarshal(m, b)
}
func (m *ResourceTopologyNodeDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceTopologyNodeDescriptor.Marshal(b, m, deterministic)
}
func (m *ResourceTopologyNodeDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceTopologyNodeDescriptor.Merge(m, src)
}
func (m *ResourceTopologyNodeDescriptor) XXX_Size() int {
	return xxx_messageInfo_ResourceTopologyNodeDescriptor.Size(m)
}
func (m *ResourceTopologyNodeDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceTopologyNodeDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceTopologyNodeDescriptor proto.InternalMessageInfo

func (m *ResourceTopologyNodeDescriptor) GetResourceDesc() *ResourceDescriptor {
	if m != nil {
		return m.ResourceDesc
	}
	return nil
}

func (m *ResourceTopologyNodeDescriptor) GetChildren() []*ResourceTopologyNodeDescriptor {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *ResourceTopologyNodeDescriptor) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func init() {
	proto.RegisterType((*ResourceTopologyNodeDescriptor)(nil), "proto.ResourceTopologyNodeDescriptor")
}

func init() { proto.RegisterFile("resource_topology_node_desc.proto", fileDescriptor_7efed64a16c51499) }

var fileDescriptor_7efed64a16c51499 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x4a, 0x2d, 0xce,
	0x2f, 0x2d, 0x4a, 0x4e, 0x8d, 0x2f, 0xc9, 0x2f, 0xc8, 0xcf, 0xc9, 0x4f, 0xaf, 0x8c, 0xcf, 0xcb,
	0x4f, 0x49, 0x8d, 0x4f, 0x49, 0x2d, 0x4e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x52, 0xc2, 0x70, 0x95, 0x08, 0x39, 0xa5, 0x03, 0x8c, 0x5c, 0x72, 0x41, 0x50, 0xf1, 0x10,
	0xa8, 0x01, 0x7e, 0xf9, 0x29, 0xa9, 0x2e, 0xa9, 0xc5, 0xc9, 0x45, 0x99, 0x05, 0x25, 0xf9, 0x45,
	0x42, 0x76, 0x5c, 0xbc, 0x28, 0x3a, 0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x24, 0x21, 0x26,
	0xe8, 0xc1, 0x74, 0x23, 0x74, 0x04, 0xf1, 0x14, 0x21, 0x89, 0x09, 0x39, 0x72, 0x71, 0x24, 0x67,
	0x64, 0xe6, 0xa4, 0x14, 0xa5, 0xe6, 0x49, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x1b, 0xa9, 0xa2, 0x69,
	0xc5, 0x6e, 0x71, 0x10, 0x5c, 0x9b, 0x90, 0x34, 0x17, 0x67, 0x41, 0x62, 0x51, 0x6a, 0x5e, 0x49,
	0x7c, 0x66, 0x8a, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x07, 0x44, 0xc0, 0x33, 0x25, 0x89,
	0x0d, 0x6c, 0x98, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x02, 0x98, 0x50, 0x10, 0x0a, 0x01, 0x00,
	0x00,
}
