// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource_desc.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResourceDescriptor_ResourceState int32

const (
	ResourceDescriptor_RESOURCE_UNKNOWN ResourceDescriptor_ResourceState = 0
	ResourceDescriptor_RESOURCE_IDLE    ResourceDescriptor_ResourceState = 1
	ResourceDescriptor_RESOURCE_BUSY    ResourceDescriptor_ResourceState = 2
	ResourceDescriptor_RESOURCE_LOST    ResourceDescriptor_ResourceState = 3
)

var ResourceDescriptor_ResourceState_name = map[int32]string{
	0: "RESOURCE_UNKNOWN",
	1: "RESOURCE_IDLE",
	2: "RESOURCE_BUSY",
	3: "RESOURCE_LOST",
}

var ResourceDescriptor_ResourceState_value = map[string]int32{
	"RESOURCE_UNKNOWN": 0,
	"RESOURCE_IDLE":    1,
	"RESOURCE_BUSY":    2,
	"RESOURCE_LOST":    3,
}

func (x ResourceDescriptor_ResourceState) String() string {
	return proto.EnumName(ResourceDescriptor_ResourceState_name, int32(x))
}

func (ResourceDescriptor_ResourceState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eee6351d237bf030, []int{0, 0}
}

type ResourceDescriptor_ResourceType int32

const (
	ResourceDescriptor_RESOURCE_PU          ResourceDescriptor_ResourceType = 0
	ResourceDescriptor_RESOURCE_CORE        ResourceDescriptor_ResourceType = 1
	ResourceDescriptor_RESOURCE_CACHE       ResourceDescriptor_ResourceType = 2
	ResourceDescriptor_RESOURCE_NIC         ResourceDescriptor_ResourceType = 3
	ResourceDescriptor_RESOURCE_DISK        ResourceDescriptor_ResourceType = 4
	ResourceDescriptor_RESOURCE_SSD         ResourceDescriptor_ResourceType = 5
	ResourceDescriptor_RESOURCE_MACHINE     ResourceDescriptor_ResourceType = 6
	ResourceDescriptor_RESOURCE_LOGICAL     ResourceDescriptor_ResourceType = 7
	ResourceDescriptor_RESOURCE_NUMA_NODE   ResourceDescriptor_ResourceType = 8
	ResourceDescriptor_RESOURCE_SOCKET      ResourceDescriptor_ResourceType = 9
	ResourceDescriptor_RESOURCE_COORDINATOR ResourceDescriptor_ResourceType = 10
)

var ResourceDescriptor_ResourceType_name = map[int32]string{
	0:  "RESOURCE_PU",
	1:  "RESOURCE_CORE",
	2:  "RESOURCE_CACHE",
	3:  "RESOURCE_NIC",
	4:  "RESOURCE_DISK",
	5:  "RESOURCE_SSD",
	6:  "RESOURCE_MACHINE",
	7:  "RESOURCE_LOGICAL",
	8:  "RESOURCE_NUMA_NODE",
	9:  "RESOURCE_SOCKET",
	10: "RESOURCE_COORDINATOR",
}

var ResourceDescriptor_ResourceType_value = map[string]int32{
	"RESOURCE_PU":          0,
	"RESOURCE_CORE":        1,
	"RESOURCE_CACHE":       2,
	"RESOURCE_NIC":         3,
	"RESOURCE_DISK":        4,
	"RESOURCE_SSD":         5,
	"RESOURCE_MACHINE":     6,
	"RESOURCE_LOGICAL":     7,
	"RESOURCE_NUMA_NODE":   8,
	"RESOURCE_SOCKET":      9,
	"RESOURCE_COORDINATOR": 10,
}

func (x ResourceDescriptor_ResourceType) String() string {
	return proto.EnumName(ResourceDescriptor_ResourceType_name, int32(x))
}

func (ResourceDescriptor_ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eee6351d237bf030, []int{0, 1}
}

type ResourceDescriptor struct {
	Uuid                string                           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FriendlyName        string                           `protobuf:"bytes,2,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	DescriptiveName     string                           `protobuf:"bytes,3,opt,name=descriptive_name,json=descriptiveName,proto3" json:"descriptive_name,omitempty"`
	State               ResourceDescriptor_ResourceState `protobuf:"varint,4,opt,name=state,proto3,enum=proto.ResourceDescriptor_ResourceState" json:"state,omitempty"`
	TaskCapacity        uint64                           `protobuf:"varint,5,opt,name=task_capacity,json=taskCapacity,proto3" json:"task_capacity,omitempty"`
	LastHeartbeat       uint64                           `protobuf:"varint,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Type                ResourceDescriptor_ResourceType  `protobuf:"varint,7,opt,name=type,proto3,enum=proto.ResourceDescriptor_ResourceType" json:"type,omitempty"`
	Schedulable         bool                             `protobuf:"varint,8,opt,name=schedulable,proto3" json:"schedulable,omitempty"`
	CurrentRunningTasks []uint64                         `protobuf:"varint,9,rep,packed,name=current_running_tasks,json=currentRunningTasks,proto3" json:"current_running_tasks,omitempty"`
	// Stores the number of running tasks on the resources that
	// are below this node,
	NumRunningTasksBelow uint64 `protobuf:"varint,10,opt,name=num_running_tasks_below,json=numRunningTasksBelow,proto3" json:"num_running_tasks_below,omitempty"`
	NumSlotsBelow        uint64 `protobuf:"varint,11,opt,name=num_slots_below,json=numSlotsBelow,proto3" json:"num_slots_below,omitempty"`
	// Resource capacity and load tracking
	AvailableResources          *ResourceVector `protobuf:"bytes,12,opt,name=available_resources,json=availableResources,proto3" json:"available_resources,omitempty"`
	ReservedResources           *ResourceVector `protobuf:"bytes,13,opt,name=reserved_resources,json=reservedResources,proto3" json:"reserved_resources,omitempty"`
	MinAvailableResourcesBelow  *ResourceVector `protobuf:"bytes,14,opt,name=min_available_resources_below,json=minAvailableResourcesBelow,proto3" json:"min_available_resources_below,omitempty"`
	MaxAvailableResourcesBelow  *ResourceVector `protobuf:"bytes,15,opt,name=max_available_resources_below,json=maxAvailableResourcesBelow,proto3" json:"max_available_resources_below,omitempty"`
	MinUnreservedResourcesBelow *ResourceVector `protobuf:"bytes,16,opt,name=min_unreserved_resources_below,json=minUnreservedResourcesBelow,proto3" json:"min_unreserved_resources_below,omitempty"`
	MaxUnreservedResourcesBelow *ResourceVector `protobuf:"bytes,17,opt,name=max_unreserved_resources_below,json=maxUnreservedResourcesBelow,proto3" json:"max_unreserved_resources_below,omitempty"`
	ResourceCapacity            *ResourceVector `protobuf:"bytes,18,opt,name=resource_capacity,json=resourceCapacity,proto3" json:"resource_capacity,omitempty"`
	// Cost-model-specific statistics
	WhareMapStats          *WhareMapStats          `protobuf:"bytes,19,opt,name=whare_map_stats,json=whareMapStats,proto3" json:"whare_map_stats,omitempty"`
	CocoInterferenceScores *CoCoInterferenceScores `protobuf:"bytes,20,opt,name=coco_interference_scores,json=cocoInterferenceScores,proto3" json:"coco_interference_scores,omitempty"`
	// Simulation related fields
	TraceMachineId uint64 `protobuf:"varint,21,opt,name=trace_machine_id,json=traceMachineId,proto3" json:"trace_machine_id,omitempty"`
	// Resource labels
	Labels               []*Label `protobuf:"bytes,32,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceDescriptor) Reset()         { *m = ResourceDescriptor{} }
func (m *ResourceDescriptor) String() string { return proto.CompactTextString(m) }
func (*ResourceDescriptor) ProtoMessage()    {}
func (*ResourceDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee6351d237bf030, []int{0}
}

func (m *ResourceDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceDescriptor.Unmarshal(m, b)
}
func (m *ResourceDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceDescriptor.Marshal(b, m, deterministic)
}
func (m *ResourceDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceDescriptor.Merge(m, src)
}
func (m *ResourceDescriptor) XXX_Size() int {
	return xxx_messageInfo_ResourceDescriptor.Size(m)
}
func (m *ResourceDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceDescriptor proto.InternalMessageInfo

func (m *ResourceDescriptor) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ResourceDescriptor) GetFriendlyName() string {
	if m != nil {
		return m.FriendlyName
	}
	return ""
}

func (m *ResourceDescriptor) GetDescriptiveName() string {
	if m != nil {
		return m.DescriptiveName
	}
	return ""
}

func (m *ResourceDescriptor) GetState() ResourceDescriptor_ResourceState {
	if m != nil {
		return m.State
	}
	return ResourceDescriptor_RESOURCE_UNKNOWN
}

func (m *ResourceDescriptor) GetTaskCapacity() uint64 {
	if m != nil {
		return m.TaskCapacity
	}
	return 0
}

func (m *ResourceDescriptor) GetLastHeartbeat() uint64 {
	if m != nil {
		return m.LastHeartbeat
	}
	return 0
}

func (m *ResourceDescriptor) GetType() ResourceDescriptor_ResourceType {
	if m != nil {
		return m.Type
	}
	return ResourceDescriptor_RESOURCE_PU
}

func (m *ResourceDescriptor) GetSchedulable() bool {
	if m != nil {
		return m.Schedulable
	}
	return false
}

func (m *ResourceDescriptor) GetCurrentRunningTasks() []uint64 {
	if m != nil {
		return m.CurrentRunningTasks
	}
	return nil
}

func (m *ResourceDescriptor) GetNumRunningTasksBelow() uint64 {
	if m != nil {
		return m.NumRunningTasksBelow
	}
	return 0
}

func (m *ResourceDescriptor) GetNumSlotsBelow() uint64 {
	if m != nil {
		return m.NumSlotsBelow
	}
	return 0
}

func (m *ResourceDescriptor) GetAvailableResources() *ResourceVector {
	if m != nil {
		return m.AvailableResources
	}
	return nil
}

func (m *ResourceDescriptor) GetReservedResources() *ResourceVector {
	if m != nil {
		return m.ReservedResources
	}
	return nil
}

func (m *ResourceDescriptor) GetMinAvailableResourcesBelow() *ResourceVector {
	if m != nil {
		return m.MinAvailableResourcesBelow
	}
	return nil
}

func (m *ResourceDescriptor) GetMaxAvailableResourcesBelow() *ResourceVector {
	if m != nil {
		return m.MaxAvailableResourcesBelow
	}
	return nil
}

func (m *ResourceDescriptor) GetMinUnreservedResourcesBelow() *ResourceVector {
	if m != nil {
		return m.MinUnreservedResourcesBelow
	}
	return nil
}

func (m *ResourceDescriptor) GetMaxUnreservedResourcesBelow() *ResourceVector {
	if m != nil {
		return m.MaxUnreservedResourcesBelow
	}
	return nil
}

func (m *ResourceDescriptor) GetResourceCapacity() *ResourceVector {
	if m != nil {
		return m.ResourceCapacity
	}
	return nil
}

func (m *ResourceDescriptor) GetWhareMapStats() *WhareMapStats {
	if m != nil {
		return m.WhareMapStats
	}
	return nil
}

func (m *ResourceDescriptor) GetCocoInterferenceScores() *CoCoInterferenceScores {
	if m != nil {
		return m.CocoInterferenceScores
	}
	return nil
}

func (m *ResourceDescriptor) GetTraceMachineId() uint64 {
	if m != nil {
		return m.TraceMachineId
	}
	return 0
}

func (m *ResourceDescriptor) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.ResourceDescriptor_ResourceState", ResourceDescriptor_ResourceState_name, ResourceDescriptor_ResourceState_value)
	proto.RegisterEnum("proto.ResourceDescriptor_ResourceType", ResourceDescriptor_ResourceType_name, ResourceDescriptor_ResourceType_value)
	proto.RegisterType((*ResourceDescriptor)(nil), "proto.ResourceDescriptor")
}

func init() { proto.RegisterFile("resource_desc.proto", fileDescriptor_eee6351d237bf030) }

var fileDescriptor_eee6351d237bf030 = []byte{
	// 778 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x4f, 0x73, 0xeb, 0x34,
	0x14, 0xc5, 0x49, 0x93, 0xf6, 0xb5, 0x37, 0xff, 0x54, 0x25, 0x7d, 0x68, 0xca, 0xbc, 0x37, 0x9e,
	0x02, 0x8f, 0xb0, 0x79, 0x8b, 0x32, 0x6c, 0x18, 0x58, 0xa4, 0x4e, 0xa0, 0x99, 0xa6, 0x31, 0x23,
	0x27, 0x14, 0x58, 0xa0, 0x51, 0x1c, 0x95, 0x7a, 0x88, 0xe5, 0x8c, 0x64, 0xb7, 0xcd, 0x77, 0x66,
	0xc1, 0x47, 0x60, 0x24, 0x3b, 0x4e, 0xd2, 0xd0, 0xb0, 0x4a, 0x7c, 0xee, 0xb9, 0x3f, 0x9f, 0xeb,
	0x91, 0x2e, 0xb4, 0x94, 0xd0, 0x71, 0xaa, 0x02, 0xc1, 0x66, 0x42, 0x07, 0x1f, 0x17, 0x2a, 0x4e,
	0x62, 0x7c, 0x68, 0x7f, 0xce, 0xdf, 0x07, 0x71, 0x10, 0xb3, 0x50, 0x26, 0x42, 0xdd, 0x0b, 0x25,
	0x64, 0x20, 0x98, 0x0e, 0x62, 0x25, 0x74, 0x66, 0x3b, 0xaf, 0xce, 0xf9, 0x54, 0xcc, 0xf3, 0x87,
	0xb3, 0x02, 0xf4, 0x28, 0x82, 0x24, 0x56, 0x2b, 0xf9, 0xe9, 0x81, 0x2b, 0xc1, 0x22, 0xbe, 0x60,
	0x3a, 0xe1, 0x49, 0xde, 0x7a, 0xf1, 0x77, 0x0d, 0x30, 0xcd, 0x1b, 0x7a, 0x42, 0x07, 0x2a, 0x5c,
	0x24, 0xb1, 0xc2, 0x18, 0x2a, 0x69, 0x1a, 0xce, 0x48, 0xc9, 0x29, 0x75, 0x4e, 0xa8, 0xfd, 0x8f,
	0x3f, 0x87, 0xfa, 0xbd, 0x0a, 0x85, 0x9c, 0xcd, 0x97, 0x4c, 0xf2, 0x48, 0x90, 0x03, 0x5b, 0xac,
	0xad, 0xc4, 0x11, 0x8f, 0x04, 0xfe, 0x1a, 0xd0, 0x2c, 0xc7, 0x84, 0x8f, 0x22, 0xf3, 0x95, 0xad,
	0xaf, 0xb9, 0xa1, 0x5b, 0xeb, 0x0f, 0x70, 0x68, 0x92, 0x08, 0x52, 0x71, 0x4a, 0x9d, 0xc6, 0xe5,
	0x57, 0x59, 0xa2, 0x8f, 0xbb, 0x69, 0x0a, 0xc9, 0x37, 0x76, 0x9a, 0x75, 0x99, 0x38, 0x09, 0xd7,
	0x7f, 0xb1, 0x80, 0x2f, 0x78, 0x10, 0x26, 0x4b, 0x72, 0xe8, 0x94, 0x3a, 0x15, 0x5a, 0x33, 0xa2,
	0x9b, 0x6b, 0xf8, 0x4b, 0x68, 0xcc, 0xb9, 0x4e, 0xd8, 0x83, 0xe0, 0x2a, 0x99, 0x0a, 0x9e, 0x90,
	0x23, 0xeb, 0xaa, 0x1b, 0xf5, 0x7a, 0x25, 0xe2, 0xef, 0xa0, 0x92, 0x2c, 0x17, 0x82, 0xbc, 0xb1,
	0x49, 0x3e, 0xfc, 0x7f, 0x92, 0xf1, 0x72, 0x21, 0xa8, 0xed, 0xc1, 0x0e, 0x54, 0x75, 0xf0, 0x20,
	0x66, 0xe9, 0x9c, 0x4f, 0xe7, 0x82, 0x1c, 0x3b, 0xa5, 0xce, 0x31, 0xdd, 0x94, 0xf0, 0x25, 0x9c,
	0x05, 0xa9, 0x52, 0x42, 0x26, 0x4c, 0xa5, 0x52, 0x86, 0xf2, 0x4f, 0x66, 0x42, 0x6a, 0x72, 0xe2,
	0x94, 0x3b, 0x15, 0xda, 0xca, 0x8b, 0x34, 0xab, 0x8d, 0x4d, 0x09, 0x7f, 0x0b, 0x9f, 0xca, 0x34,
	0xda, 0xf6, 0xb3, 0xa9, 0x98, 0xc7, 0x4f, 0x04, 0xec, 0x04, 0x6d, 0x99, 0x46, 0x9b, 0x1d, 0x57,
	0xa6, 0x86, 0x3f, 0x40, 0xd3, 0xb4, 0xe9, 0x79, 0x9c, 0xac, 0xec, 0xd5, 0x6c, 0x60, 0x99, 0x46,
	0xbe, 0x51, 0x33, 0xdf, 0x8f, 0xd0, 0xe2, 0x8f, 0x3c, 0xb4, 0xf9, 0xd8, 0xea, 0xc0, 0x68, 0x52,
	0x73, 0x4a, 0x9d, 0xea, 0xe5, 0xd9, 0x8b, 0xf9, 0x7f, 0xb1, 0xe7, 0x88, 0xe2, 0xa2, 0x63, 0x55,
	0xd0, 0xb8, 0x07, 0x58, 0x09, 0x2d, 0xd4, 0xa3, 0x98, 0x6d, 0x60, 0xea, 0xfb, 0x30, 0xa7, 0xab,
	0x86, 0x35, 0xe5, 0x57, 0x78, 0x17, 0x85, 0x92, 0xfd, 0x47, 0xa2, 0x7c, 0x86, 0xc6, 0x3e, 0xe0,
	0x79, 0x14, 0xca, 0xee, 0x4e, 0xb4, 0x6c, 0x4e, 0x43, 0xe6, 0xcf, 0x7b, 0xc8, 0xcd, 0xfd, 0x64,
	0xfe, 0xfc, 0x1a, 0xf9, 0x77, 0x78, 0x6f, 0x32, 0xa7, 0x72, 0x77, 0xfe, 0x1c, 0x8d, 0xf6, 0xa1,
	0x3f, 0x8b, 0x42, 0x39, 0x91, 0x3b, 0x9f, 0x62, 0xcd, 0xe6, 0xcf, 0xfb, 0xd8, 0xa7, 0xfb, 0xd9,
	0xfc, 0xf9, 0x55, 0xf6, 0x15, 0x9c, 0x16, 0x0b, 0xa2, 0xb8, 0x3a, 0x78, 0x1f, 0x0e, 0xad, 0xfc,
	0xc5, 0xad, 0xfa, 0x1e, 0x9a, 0x2f, 0xb6, 0x09, 0x69, 0x59, 0x42, 0x3b, 0x27, 0xdc, 0x99, 0xea,
	0x2d, 0x5f, 0x98, 0x0b, 0xab, 0x69, 0xfd, 0x69, 0xf3, 0x11, 0xdf, 0x01, 0x79, 0x6d, 0x9f, 0x91,
	0xb6, 0xc5, 0xbc, 0xcb, 0x31, 0x6e, 0xec, 0xc6, 0x83, 0x0d, 0x97, 0x6f, 0x4d, 0xf4, 0xad, 0x69,
	0xdf, 0xd5, 0x71, 0x07, 0x50, 0xa2, 0x78, 0x60, 0x62, 0x05, 0x0f, 0xa1, 0x14, 0x2c, 0x9c, 0x91,
	0x33, 0x7b, 0xfa, 0x1b, 0x56, 0xbf, 0xcd, 0xe4, 0xc1, 0x0c, 0x7f, 0x01, 0x47, 0x76, 0x65, 0x6a,
	0xe2, 0x38, 0xe5, 0x4e, 0xf5, 0xb2, 0x96, 0xbf, 0x70, 0x68, 0x44, 0x9a, 0xd7, 0x2e, 0xfe, 0x80,
	0xfa, 0xd6, 0xe6, 0xc1, 0x6d, 0x40, 0xb4, 0xef, 0x7b, 0x13, 0xea, 0xf6, 0xd9, 0x64, 0x74, 0x33,
	0xf2, 0xee, 0x46, 0xe8, 0x13, 0x7c, 0x0a, 0xf5, 0x42, 0x1d, 0xf4, 0x86, 0x7d, 0x54, 0xda, 0x92,
	0xae, 0x26, 0xfe, 0x6f, 0xe8, 0x60, 0x4b, 0x1a, 0x7a, 0xfe, 0x18, 0x95, 0x2f, 0xfe, 0x29, 0x41,
	0x6d, 0x73, 0xa1, 0xe0, 0x26, 0x54, 0x0b, 0xcf, 0xcf, 0x93, 0x17, 0x68, 0xd7, 0xa3, 0x06, 0x8d,
	0xa1, 0xb1, 0x96, 0xba, 0xee, 0x75, 0x1f, 0x1d, 0x60, 0x04, 0xb5, 0x42, 0x1b, 0x0d, 0x5c, 0x54,
	0xde, 0x6a, 0xec, 0x0d, 0xfc, 0x1b, 0x54, 0xd9, 0x32, 0xf9, 0x7e, 0x0f, 0x1d, 0x6e, 0x8d, 0x73,
	0xdb, 0x75, 0xaf, 0x07, 0xa3, 0x3e, 0x3a, 0xda, 0x52, 0x87, 0xde, 0x4f, 0x03, 0xb7, 0x3b, 0x44,
	0x6f, 0xf0, 0x5b, 0xc0, 0xeb, 0x57, 0x4c, 0x6e, 0xbb, 0x6c, 0xe4, 0xf5, 0xfa, 0xe8, 0x18, 0xb7,
	0xa0, 0xb9, 0xa6, 0x7a, 0xee, 0x4d, 0x7f, 0x8c, 0x4e, 0x30, 0x81, 0xf6, 0x46, 0x6c, 0x8f, 0xf6,
	0x06, 0xa3, 0xee, 0xd8, 0xa3, 0x08, 0xa6, 0x47, 0xf6, 0x3b, 0x7f, 0xf3, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x64, 0x81, 0xef, 0x86, 0xee, 0x06, 0x00, 0x00,
}
