// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduling_delta.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SchedulingDelta_ChangeType int32

const (
	SchedulingDelta_NOOP    SchedulingDelta_ChangeType = 0
	SchedulingDelta_PLACE   SchedulingDelta_ChangeType = 1
	SchedulingDelta_PREEMPT SchedulingDelta_ChangeType = 2
	SchedulingDelta_MIGRATE SchedulingDelta_ChangeType = 3
)

var SchedulingDelta_ChangeType_name = map[int32]string{
	0: "NOOP",
	1: "PLACE",
	2: "PREEMPT",
	3: "MIGRATE",
}

var SchedulingDelta_ChangeType_value = map[string]int32{
	"NOOP":    0,
	"PLACE":   1,
	"PREEMPT": 2,
	"MIGRATE": 3,
}

func (x SchedulingDelta_ChangeType) String() string {
	return proto.EnumName(SchedulingDelta_ChangeType_name, int32(x))
}

func (SchedulingDelta_ChangeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9f86c8a6a6ba2880, []int{0, 0}
}

type SchedulingDelta struct {
	TaskId               uint64                     `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ResourceId           string                     `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Type                 SchedulingDelta_ChangeType `protobuf:"varint,3,opt,name=type,proto3,enum=proto.SchedulingDelta_ChangeType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SchedulingDelta) Reset()         { *m = SchedulingDelta{} }
func (m *SchedulingDelta) String() string { return proto.CompactTextString(m) }
func (*SchedulingDelta) ProtoMessage()    {}
func (*SchedulingDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f86c8a6a6ba2880, []int{0}
}

func (m *SchedulingDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulingDelta.Unmarshal(m, b)
}
func (m *SchedulingDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulingDelta.Marshal(b, m, deterministic)
}
func (m *SchedulingDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulingDelta.Merge(m, src)
}
func (m *SchedulingDelta) XXX_Size() int {
	return xxx_messageInfo_SchedulingDelta.Size(m)
}
func (m *SchedulingDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulingDelta.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulingDelta proto.InternalMessageInfo

func (m *SchedulingDelta) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *SchedulingDelta) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *SchedulingDelta) GetType() SchedulingDelta_ChangeType {
	if m != nil {
		return m.Type
	}
	return SchedulingDelta_NOOP
}

func init() {
	proto.RegisterEnum("proto.SchedulingDelta_ChangeType", SchedulingDelta_ChangeType_name, SchedulingDelta_ChangeType_value)
	proto.RegisterType((*SchedulingDelta)(nil), "proto.SchedulingDelta")
}

func init() { proto.RegisterFile("scheduling_delta.proto", fileDescriptor_9f86c8a6a6ba2880) }

var fileDescriptor_9f86c8a6a6ba2880 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4e, 0xce, 0x48,
	0x4d, 0x29, 0xcd, 0xc9, 0xcc, 0x4b, 0x8f, 0x4f, 0x49, 0xcd, 0x29, 0x49, 0xd4, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xfb, 0x19, 0xb9, 0xf8, 0x83, 0xe1, 0x2a, 0x5c, 0x40,
	0x0a, 0x84, 0xc4, 0xb9, 0xd8, 0x4b, 0x12, 0x8b, 0xb3, 0xe3, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x58, 0x82, 0xd8, 0x40, 0x5c, 0xcf, 0x14, 0x21, 0x79, 0x2e, 0xee, 0xa2, 0xd4, 0xe2, 0xfc,
	0xd2, 0xa2, 0xe4, 0x54, 0x90, 0x24, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x17, 0x4c, 0xc8, 0x33,
	0x45, 0xc8, 0x94, 0x8b, 0xa5, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0xcf, 0x48,
	0x11, 0x62, 0x95, 0x1e, 0x9a, 0xf9, 0x7a, 0xce, 0x19, 0x89, 0x79, 0xe9, 0xa9, 0x21, 0x95, 0x05,
	0xa9, 0x41, 0x60, 0xe5, 0x4a, 0xd6, 0x5c, 0x5c, 0x08, 0x31, 0x21, 0x0e, 0x2e, 0x16, 0x3f, 0x7f,
	0xff, 0x00, 0x01, 0x06, 0x21, 0x4e, 0x2e, 0xd6, 0x00, 0x1f, 0x47, 0x67, 0x57, 0x01, 0x46, 0x21,
	0x6e, 0x2e, 0xf6, 0x80, 0x20, 0x57, 0x57, 0xdf, 0x80, 0x10, 0x01, 0x26, 0x10, 0xc7, 0xd7, 0xd3,
	0x3d, 0xc8, 0x31, 0xc4, 0x55, 0x80, 0x39, 0x89, 0x0d, 0x6c, 0x89, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xf2, 0x21, 0x82, 0x79, 0xe9, 0x00, 0x00, 0x00,
}
