// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task_final_report.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskFinalReport struct {
	TaskId               uint64   `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StartTime            uint64   `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FinishTime           uint64   `protobuf:"varint,3,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	Instructions         uint64   `protobuf:"varint,4,opt,name=instructions,proto3" json:"instructions,omitempty"`
	Cycles               uint64   `protobuf:"varint,5,opt,name=cycles,proto3" json:"cycles,omitempty"`
	LlcRefs              uint64   `protobuf:"varint,6,opt,name=llc_refs,json=llcRefs,proto3" json:"llc_refs,omitempty"`
	LlcMisses            uint64   `protobuf:"varint,7,opt,name=llc_misses,json=llcMisses,proto3" json:"llc_misses,omitempty"`
	Runtime              float64  `protobuf:"fixed64,8,opt,name=runtime,proto3" json:"runtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskFinalReport) Reset()         { *m = TaskFinalReport{} }
func (m *TaskFinalReport) String() string { return proto.CompactTextString(m) }
func (*TaskFinalReport) ProtoMessage()    {}
func (*TaskFinalReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c14910be0bbf67e, []int{0}
}

func (m *TaskFinalReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskFinalReport.Unmarshal(m, b)
}
func (m *TaskFinalReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskFinalReport.Marshal(b, m, deterministic)
}
func (m *TaskFinalReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskFinalReport.Merge(m, src)
}
func (m *TaskFinalReport) XXX_Size() int {
	return xxx_messageInfo_TaskFinalReport.Size(m)
}
func (m *TaskFinalReport) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskFinalReport.DiscardUnknown(m)
}

var xxx_messageInfo_TaskFinalReport proto.InternalMessageInfo

func (m *TaskFinalReport) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *TaskFinalReport) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *TaskFinalReport) GetFinishTime() uint64 {
	if m != nil {
		return m.FinishTime
	}
	return 0
}

func (m *TaskFinalReport) GetInstructions() uint64 {
	if m != nil {
		return m.Instructions
	}
	return 0
}

func (m *TaskFinalReport) GetCycles() uint64 {
	if m != nil {
		return m.Cycles
	}
	return 0
}

func (m *TaskFinalReport) GetLlcRefs() uint64 {
	if m != nil {
		return m.LlcRefs
	}
	return 0
}

func (m *TaskFinalReport) GetLlcMisses() uint64 {
	if m != nil {
		return m.LlcMisses
	}
	return 0
}

func (m *TaskFinalReport) GetRuntime() float64 {
	if m != nil {
		return m.Runtime
	}
	return 0
}

func init() {
	proto.RegisterType((*TaskFinalReport)(nil), "proto.TaskFinalReport")
}

func init() { proto.RegisterFile("task_final_report.proto", fileDescriptor_3c14910be0bbf67e) }

var fileDescriptor_3c14910be0bbf67e = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x85, 0x89, 0xde, 0xed, 0x9e, 0xa3, 0x20, 0xa4, 0xf0, 0x62, 0x21, 0x1e, 0x57, 0x5d, 0x65,
	0xe3, 0x7f, 0x10, 0x2c, 0x6c, 0x96, 0xeb, 0x97, 0x35, 0x97, 0xe0, 0x70, 0xb3, 0xc9, 0x91, 0x99,
	0x2d, 0xfc, 0xeb, 0x56, 0x92, 0x09, 0x16, 0x56, 0xe1, 0xbd, 0xef, 0x0b, 0x79, 0x04, 0xb6, 0x32,
	0xf1, 0x79, 0x8c, 0x98, 0x26, 0x1a, 0x4b, 0xb8, 0xe4, 0x22, 0x2f, 0x97, 0x92, 0x25, 0xdb, 0xb5,
	0x1e, 0xfb, 0x1f, 0x03, 0xf7, 0xc7, 0x89, 0xcf, 0x6f, 0xd5, 0x18, 0x54, 0xb0, 0x5b, 0xe8, 0xf5,
	0x16, 0x9e, 0x9c, 0xd9, 0x99, 0xc3, 0x6a, 0xe8, 0x6a, 0x7c, 0x3f, 0xd9, 0x27, 0x00, 0x96, 0xa9,
	0xc8, 0x28, 0x38, 0x07, 0x77, 0xa5, 0xec, 0x46, 0x9b, 0x23, 0xce, 0xc1, 0x3e, 0xc3, 0x6d, 0xc4,
	0x84, 0xfc, 0xd5, 0xf8, 0xb5, 0x72, 0x68, 0x95, 0x0a, 0x7b, 0xb8, 0xc3, 0xc4, 0x52, 0x16, 0x2f,
	0x98, 0x13, 0xbb, 0x95, 0x1a, 0xff, 0x3a, 0xfb, 0x00, 0x9d, 0xff, 0xf6, 0x14, 0xd8, 0xad, 0xdb,
	0xdb, 0x2d, 0xd9, 0x47, 0xd8, 0x10, 0xf9, 0xb1, 0x84, 0xc8, 0xae, 0x53, 0xd2, 0x13, 0xf9, 0x21,
	0x44, 0xae, 0xb3, 0x2a, 0x9a, 0x91, 0x39, 0xb0, 0xeb, 0xdb, 0x2c, 0x22, 0xff, 0xa1, 0x85, 0x75,
	0xd0, 0x97, 0x25, 0xe9, 0xa4, 0xcd, 0xce, 0x1c, 0xcc, 0xf0, 0x17, 0x3f, 0x3b, 0xfd, 0x83, 0xd7,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xf8, 0x90, 0xcc, 0x25, 0x01, 0x00, 0x00,
}
