// Code generated by protoc-gen-go. DO NOT EDIT.
// source: whare_map_stats.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WhareMapStats struct {
	NumIdle              uint64   `protobuf:"varint,1,opt,name=num_idle,json=numIdle,proto3" json:"num_idle,omitempty"`
	NumDevils            uint64   `protobuf:"varint,2,opt,name=num_devils,json=numDevils,proto3" json:"num_devils,omitempty"`
	NumRabbits           uint64   `protobuf:"varint,3,opt,name=num_rabbits,json=numRabbits,proto3" json:"num_rabbits,omitempty"`
	NumSheep             uint64   `protobuf:"varint,4,opt,name=num_sheep,json=numSheep,proto3" json:"num_sheep,omitempty"`
	NumTurtles           uint64   `protobuf:"varint,5,opt,name=num_turtles,json=numTurtles,proto3" json:"num_turtles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhareMapStats) Reset()         { *m = WhareMapStats{} }
func (m *WhareMapStats) String() string { return proto.CompactTextString(m) }
func (*WhareMapStats) ProtoMessage()    {}
func (*WhareMapStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a4ceac8dff9bab, []int{0}
}

func (m *WhareMapStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhareMapStats.Unmarshal(m, b)
}
func (m *WhareMapStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhareMapStats.Marshal(b, m, deterministic)
}
func (m *WhareMapStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhareMapStats.Merge(m, src)
}
func (m *WhareMapStats) XXX_Size() int {
	return xxx_messageInfo_WhareMapStats.Size(m)
}
func (m *WhareMapStats) XXX_DiscardUnknown() {
	xxx_messageInfo_WhareMapStats.DiscardUnknown(m)
}

var xxx_messageInfo_WhareMapStats proto.InternalMessageInfo

func (m *WhareMapStats) GetNumIdle() uint64 {
	if m != nil {
		return m.NumIdle
	}
	return 0
}

func (m *WhareMapStats) GetNumDevils() uint64 {
	if m != nil {
		return m.NumDevils
	}
	return 0
}

func (m *WhareMapStats) GetNumRabbits() uint64 {
	if m != nil {
		return m.NumRabbits
	}
	return 0
}

func (m *WhareMapStats) GetNumSheep() uint64 {
	if m != nil {
		return m.NumSheep
	}
	return 0
}

func (m *WhareMapStats) GetNumTurtles() uint64 {
	if m != nil {
		return m.NumTurtles
	}
	return 0
}

func init() {
	proto.RegisterType((*WhareMapStats)(nil), "proto.WhareMapStats")
}

func init() { proto.RegisterFile("whare_map_stats.proto", fileDescriptor_d4a4ceac8dff9bab) }

var fileDescriptor_d4a4ceac8dff9bab = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0xcf, 0x48, 0x2c,
	0x4a, 0x8d, 0xcf, 0x4d, 0x2c, 0x88, 0x2f, 0x2e, 0x49, 0x2c, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x2b, 0x18, 0xb9, 0x78, 0xc3, 0x41, 0x0a, 0x7c, 0x13, 0x0b,
	0x82, 0x41, 0xd2, 0x42, 0x92, 0x5c, 0x1c, 0x79, 0xa5, 0xb9, 0xf1, 0x99, 0x29, 0x39, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0xec, 0x79, 0xa5, 0xb9, 0x9e, 0x29, 0x39, 0xa9, 0x42, 0xb2,
	0x5c, 0x5c, 0x20, 0xa9, 0x94, 0xd4, 0xb2, 0xcc, 0x9c, 0x62, 0x09, 0x26, 0xb0, 0x24, 0x67, 0x5e,
	0x69, 0xae, 0x0b, 0x58, 0x40, 0x48, 0x9e, 0x8b, 0x1b, 0x24, 0x5d, 0x94, 0x98, 0x94, 0x94, 0x59,
	0x52, 0x2c, 0xc1, 0x0c, 0x96, 0x07, 0xe9, 0x08, 0x82, 0x88, 0x08, 0x49, 0x73, 0x81, 0x54, 0xc7,
	0x17, 0x67, 0xa4, 0xa6, 0x16, 0x48, 0xb0, 0x80, 0xa5, 0x41, 0x76, 0x05, 0x83, 0xf8, 0x30, 0xdd,
	0x25, 0xa5, 0x45, 0x25, 0x39, 0xa9, 0xc5, 0x12, 0xac, 0x70, 0xdd, 0x21, 0x10, 0x91, 0x24, 0x36,
	0xb0, 0x8b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xf3, 0xad, 0x76, 0xd1, 0x00, 0x00,
	0x00,
}
